---
title: "CSDS341_Project_accessingMySQL"
author: "Luke Zhang (rxz330)"
date: "`r Sys.Date()`"
output: html_document
---
# Preliminaries 
```{r packages, message=FALSE, warning=FALSE}
library(RMySQL)
library(RODBC)
```

## Preliminaries
```{r connectio_to_sql, message=FALSE}
# Establish Connection to MySQL
mysql_connection <- dbConnect(RMySQL::MySQL(),
                              dbname='airline',
                              host='localhost', 
                              port=3306,
                              user='root', 
                              password='')

# List All the Tables in the Schema
dbListTables(mysql_connection)
```

```{r print_table, message=FALSE}
dbListFields(mysql_connection,"travelers")
```

```{r}
# Query 01: Find all male travelers who are U.S. citizen. 
sql_01 <- "SELECT * 
           FROM travelers
           WHERE citizenship = 'US' AND gender = 'M'"

result_01 <- dbSendQuery(mysql_connection, sql)

output_01 <- fetch(result_01)
output_01 %>% kable()
```


```{r}

#result = dbSendQuery(mysqlconnection, "select * from course") # write query to acces the records from a particular table.

#data.frame = fetch(result, n = 5)
#print(data.frame)                # Store the result in a R data frame object. n = 5 is used to fetch first 5 rows.
```

